version: '3.3'

services:
  # myslq
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '9000:3306'
    expose:
      - '9000'
    volumes:
      - ./data:/var/lib/mysql

   # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '9001:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 

volumes:
  my-db:
